name: Build and deploy to Live server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: npm install
      - run: npm run test
     
      - name: Install SSH Key
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}
          known_hosts: 'placeholder'

      - name: Set up SSH Known Host
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} >> ~/.ssh/known_hosts

      - name: Create auth file
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: |
          echo $AUTH_FILE >> ./auth.json
        shell: bash
        env:
          AUTH_FILE: ${{ secrets.JSON_AUTH }}

      - name: Deploy
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/deploy/bot/

      - name: Restart Bot
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/deploy/bot/
            pm2 stop bot
            git fetch origin main
            git reset --hard FETCH_HEAD
            git clean -d -f
            npm install --omit=dev
            npm run start-prod
